package com.example.Tji_Teliman.entites.enums;

public enum TypeSignalement {
    CONTENU_INAPPROPRIE_OU_MISSION_ILLEGAL,
    ARNAQUE_OU_FRAUDE_POTENTIELLE,
    DEMANDE_D_INFORMATIONS_PERSONNELLES,
    NON_RESPECT_DES_CONDITIONS_D_UTILISATION,
    PRIX_IRREALISTE_OU_INCOHERENT,
    AUTRE
}


